### PR TITLE
Update interactive module

### PR DESCRIPTION
**Pull request by joaander**
## Description

Fix the interactive module to allow rotations again.

Also:
 * Use a low resolution render while the user is adjusting the camera to improve the latency for the user.
 * Make rotations to the camera from the point the user clicks. Now, you can click and drag and make any number of mouse motions - returning to the original position while still holding the button will return the view back to the original view.

Resolves: #114 

## Checklist:
- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/fresnel/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Fresnel Contributor Agreement**](https://github.com/glotzerlab/fresnel/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of authors](https://github.com/glotzerlab/fresnel/blob/master/doc/credits.rst).

### CODE REVIEW

**Comment by joaander** [comment]
@jennyfothergill This fixes the rotation issue in interact on `master`. Next up, I'm going to see if I can improve the latency while rotating.
@tcmoore3 You once mentioned that the interact widget's mouse operation was not intuitive. What changes would you recommend to improve it?

**Comment by jennyfothergill** [comment]
OK, I've played with these changes (they're AWESOME 🤩) and have the new fresnel interact module working in GIXStapose (as of commit e3f2a5f) https://github.com/jennyfothergill/GIXStapose/tree/fix/interact

**Comment by tcmoore3** [comment]
@joaander I vaguely remember making that comment a long time ago, but I don't remember what made it feel unnatural. I'll play with it and see if I still feel the same.

**Comment by joaander** [comment]
> @joaander I vaguely remember making that comment a long time ago, but I don't remember what made it feel unnatural. I'll play with it and see if I still feel the same.

The implementation in the release makes many small rotations on every mouse delta move. This means that when you click and hold, drag the mouse around, and then return the mouse to the original position where you clicked the camera does not return to the same place. In this PR, it records the camera position when you click and then makes large rotations given the delta between the mouse's current position and the position of the click - so when you return the mouse to the position you clicked the camera is back in its original position. 

Perhaps this is the problem you are referring to? If not, let me know. I haven't yet tried using something like OVITO and fresnel side by side to see if they behave similarly or differently.

**Comment by tcmoore3** [comment]
OK, I was able to get everything working nicely together (just a fresh conda env) to test out the interactive module. I like the updates. The rotations feel natural and it's nice to get a rough sense of the new angle while you're rotating. I haven't tested on a GPU but it's nice on my laptop.

**Comment by tcmoore3** [comment]
I accidentally clicked "ready for review" and now changed it back to a draft.

**Comment by joaander** [comment]
Thanks for taking the time to test this. I think the branch is ready to review now. I've been focusing on HOOMD dev for now, so I'm not sure what all needs to be done to polish this PR off.

**Comment by joaander** [comment]
Thanks for reviewing. I will come back to this after releasing hoomd v3.0-beta.1

**Pull request merged**
