### PR TITLE
Implement perspective camera

### PR DESCRIPTION
**Pull request by joaander**
## Description

The thin lens camera model enables depth of field in the path trace rendering. The pinhole camera model implements a perspective camera that is in focus at all distances.

This is a work in progress. I still plan to add additional documentation, examples and possibly refactor the API.

Resolves: #30 

## Preview

Depth of field can be used to emphasis the important parts of an image and de-emphasis the less important parts. Here is the fresnel-examples cube with depth of field rendering enabled.

cube

## Change log

```
* Perspective camera.
* Depth of field effect.
```

## Checklist:
- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/fresnel/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Fresnel Contributor Agreement**](https://github.com/glotzerlab/fresnel/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of authors](https://github.com/glotzerlab/fresnel/blob/master/doc/credits.rst).

### CODE REVIEW

**Comment by joaander** [comment]
> 
> 
> This is really cool. I was curious how this worked! 📷👍

This is the clearest guide I found: https://courses.cs.washington.edu/courses/csep557/99au/projects/trace/depthoffield.doc
I was surprised at how straightforward the implementation using the construction of the convergence point.

**Comment by joaander** [comment]
New camera documentation preview:
https://fresnel.readthedocs.io/en/camera-models/module-camera.html
@vyasr does this clarify the confusions in the original documentation? Do you have any suggestions for improvement?

**Comment by vyasr** [comment]
I would add what controls the width of the image plane. Also, do you by any chance still have the ppt you made while we discussed? I think seeing that again (and having it jog my memory of our discussion) would give me additional ideas. This does help with what I recall being my principal confusion, though, which was that height is orthogonal to the look at distance.

**Comment by joaander** [comment]
This is ready for review. Reviewers, please:
* Review the new `Camera` API and its [documentation](https://fresnel.readthedocs.io/en/camera-models/module-camera.html)
* Make spelling and grammar changes directly on the branch.
* Ignore code and docstring style issues, I will be re-running formatters and linters with a new configuration in a follow up PR (#111)

Questions to address in your review:
* With the new class hierarchy based cameras (`Orthographic` and `Perspective`), I removed the default 'auto' scene camera for consistency (the `camera` property is a `Camera`). To get the old auto behavior, users now need to explicitly set `scene.camera = fresnel.camera.Orthographic.fit(scene)`. Does this change make sense to you? If not, what API would you propose?
* Should the `Preview` tracer also have depth of field effects? If yes, we would need to undo the recent change to the boolean `anti_alias` option and instead take a number of samples. Anti-aliasing and depth of field are both implemented by Monte Carlo sampling.

**Pull request merged**
