### PR TITLE
Gallery improvements

### PR DESCRIPTION
**Pull request by joaander**
## Description

* Add [nature chemistry cover art](https://www.nature.com/nchem/volumes/11/issues/3) to the gallery
* Add thumbnails to documentation index
* Showcase high-res images
* Fix a mislabeled documentation section

## Preview

* [README preview](https://github.com/glotzerlab/fresnel/blob/gallery-improvements/README.md)
* [readthedocs preview](https://fresnel.readthedocs.io/en/gallery-improvements/)

## Proposed change log entries

```
* Documentation improvements
```

Reviewers, feel free to make obvious improvements directly on the branch.

### CODE REVIEW

**Comment by joaander** [comment]
@bdice, @mikemhenry: which gallery layout(s) would be most useful?

* 3xN demo in [index](https://fresnel.readthedocs.io/en/gallery-improvements/index.html) and [readme](https://github.com/glotzerlab/fresnel/blob/gallery-improvements/README.md)
* [2xN with descriptions](https://fresnel.readthedocs.io/en/gallery-improvements/gallery-alternate.html)
* 1xN with descriptions [demo category 1](https://fresnel.readthedocs.io/en/gallery-improvements/gallery-research.html) and [demo category 2](https://fresnel.readthedocs.io/en/gallery-improvements/gallery-features.html)

**Comment by bdice** [comment]
I like the 3xN and 1xN but not the 2xN with descriptions. I would like the index / README to have two rows of three images at most, with a link to a Gallery for a longer 3xN set of images.

Another source of inspiration: https://docs.enthought.com/mayavi/mayavi/auto/examples.html

**Comment by joaander** [comment]
@jglaser Would you mind sharing the material parameters you used? https://fresnel.readthedocs.io/en/gallery-improvements/gallery/protomer.html

**Comment by jglaser** [comment]
> @jglaser Would you mind sharing the material parameters you used? https://fresnel.readthedocs.io/en/gallery-improvements/gallery/protomer.html

Ribbons:
roughness 1.0, specular=1.0, metal=0, spec_trans=0

Molecular surface:
roughness = 2 (<- is this clipped?)
spec = .95
metal = 0
spec_trans = 0.95

Lighting:
`fresnel.light.lightbox()` with background light

Rendering: `fresnel.pathtrace` samples=64, light_samples=32 on GPU

**Comment by jglaser** [comment]
> > @jglaser Would you mind sharing the material parameters you used? https://fresnel.readthedocs.io/en/gallery-improvements/gallery/protomer.html
> 
> Ribbons:
> roughness 1.0, specular=1.0, metal=0, spec_trans=0
> 
> Molecular surface:
> roughness = 2 (<- is this clipped?)
> spec = .95
> metal = 0
> spec_trans = 0.95
> 
> Lighting:
> `fresnel.light.lightbox()` with background light
> 
> Rendering: `fresnel.pathtrace` samples=64, light_samples=32 on GPU

Ribbons generated with https://github.com/fogleman/ribbon
Molecular surface generated with msms https://mgl.scripps.edu/people/sanner/html/msms_home.html

**Comment by mikemhenry** [comment]
That looks great! I really like the style of pretty picture -> link to the code that made it. That kind of workflow lets people see what is possible and then how to do it.

**Comment by joaander** [comment]
Thanks! I think this is done.

> roughness = 2 (<- is this clipped?)
No. The nominal range is 0.1-1 for roughness, but larger values do produce visibly different results.

**Pull request merged**
